name: Deploy Microservices

on:
  push:
    branches: [main]

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: SSH Deploy
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST_NAME: ${{ secrets.SSH_HOST }}
          USER_NAME: ${{ secrets.USER_NAME }}
          PROJECT_PATH: ${{ secrets.PROJECT_PATH }}
          GIT_REPO: ${{ secrets.GIT_REPO }}
        run: |
          # Create .ssh directory
          mkdir -p ~/.ssh
          
          # Write key to file and set proper permissions
          echo "$PRIVATE_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          
          # Add host to known hosts
          ssh-keyscan -H ${HOST_NAME} >> ~/.ssh/known_hosts
          
          # Use -T flag to disable pseudo-terminal allocation
          ssh -T -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key ${USER_NAME}@${HOST_NAME} <<EOF
            if [ ! -d "${PROJECT_PATH}/.git" ]; then
              mkdir -p \$(dirname ${PROJECT_PATH})
              git clone ${GIT_REPO} ${PROJECT_PATH}
            fi

            cd ${PROJECT_PATH}
            git checkout main
            git fetch --all
            git reset --hard origin/main
            git pull origin main

            # Microservices
            # backend-check-in
            if [ ! -d "${PROJECT_PATH}/backend-check-in/.git" ]; then
              mkdir -p \$(dirname ${PROJECT_PATH}/backend-check-in)
              git clone ${GIT_REPO_CHECK_IN} ${PROJECT_PATH}/backend-check-in
            fi

            cd ${PROJECT_PATH}/backend-check-in
            git checkout develop
            git fetch --all
            git reset --hard origin/develop
            git pull origin develop

            # backend-user 
            if [ ! -d "${PROJECT_PATH}/backend-user/.git" ]; then
              mkdir -p \$(dirname ${PROJECT_PATH}/backend-user)
              git clone ${GIT_REPO_USER} ${PROJECT_PATH}/backend-user
            fi

            cd ${PROJECT_PATH}/backend-user
            git checkout develop
            git fetch --all
            git reset --hard origin/develop
            git pull origin develop

            # backend-payroll
            if [ ! -d "${PROJECT_PATH}/backend-payroll/.git" ]; then
              mkdir -p \$(dirname ${PROJECT_PATH}/backend-payroll)
              git clone ${GIT_REPO_PAYROLL} ${PROJECT_PATH}/backend-payroll
            fi

            cd ${PROJECT_PATH}/backend-payroll
            git checkout develop
            git fetch --all
            git reset --hard origin/develop
            git pull origin develop

            # backend-goals
            if [ ! -d "${PROJECT_PATH}/backend-goals/.git" ]; then
              mkdir -p \$(dirname ${PROJECT_PATH}/backend-goals)
              git clone ${GIT_REPO_GOALS} ${PROJECT_PATH}/backend-goals
            fi

            cd ${PROJECT_PATH}/backend-goals
            git checkout develop
            git fetch --all
            git reset --hard origin/develop
            git pull origin develop 


            cd ${PROJECT_PATH}

            make remove-network
            make create-network

            make down-all
            make up-all
          
          EOF